### ISSUE TITLE
Case for which it approves the loan?

### ISSUE THREAD

**Issue by Arvind422** [AIVenture0/Loan-defaulter-prediction-Web-App#2]
Sir in which case will it provide the user with loan? I have tried many but for all its just rejecting the loan application...pls tell me the case for which it provides loan!!! @AIVenture0  @vikramvinay  pls answer

**Comment by AIVenture0** [comment]
As the Data is highly Biased __(90:10)__ for this case so the chances to get such case is very rare.. I Suggest you choose some data from the original dataset it self for Loan Approval and then try to play around it.
